-- ALL USERS TABLE
CREATE TABLE Users (
	UserID INT IDENTITY(1,1) PRIMARY KEY,
	Username NVARCHAR(50) NOT NULL UNIQUE,
	Email NVARCHAR(100) NOT NULL UNIQUE,
	PasswordHash NVARCHAR(255) NOT NULL,
	Role NVARCHAR(20) NOT NULL,	
	Status NVARCHAR(20) DEFAULT 'Pending',
	CreatedAt DATETIME DEFAULT GETDATE()
);

-- ADMIN TABLES
CREATE TABLE ActivityLogs (
	LogID INT IDENTITY(1,1) PRIMARY KEY,
	UserID INT FOREIGN KEY REFERENCES Users(UserID),
	Action NVARCHAR(100),
	Timestamp DATETIME DEFAULT GETDATE(),
	Details NVARCHAR(MAX)
);

CREATE TABLE VerificationLog (
	ModerationID INT IDENTITY(1,1) PRIMARY KEY,
	TargetID INT NOT NULL,
	TargetType NVARCHAR(50) NOT NULL,
	AdminID INT FOREIGN KEY REFERENCES Users(UserID),
	Status NVARCHAR(20),
	Comments NVARCHAR(MAX),
	ReviewedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE UserReports (
	ReportID INT IDENTITY (1,1) PRIMARY KEY,
	ReporterID INT FOREIGN KEY REFERENCES Users(UserID),
	ReportedEntityID INT NOT NULL,
	Reason NVARCHAR(MAX),
	Status NVARCHAR(20) DEFAULT 'Open'
);

-- INSTRUCTOR TABLES
CREATE TABLE LearningContent (
	ContentID INT IDENTITY (1,1) PRIMARY KEY,
	LecturerID INT FOREIGN KEY REFERENCES Users(UserID),
	Title NVARCHAR(200) NOT NULL,
	Description NVARCHAR(MAX),
	ContentType NVARCHAR(50),
	FilePath NVARCHAR(300),
	Url NVARCHAR(500),
	IsPublished BIT DEFAULT 0,
	CreatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE Assessment (
	AssessmentID INT IDENTITY (1,1) PRIMARY KEY,
	LecturerID INT FOREIGN KEY REFERENCES Users(UserID),
	Title NVARCHAR(200) NOT NULL,
	AssessmentType NVARCHAR(50),
	Instructions NVARCHAR(MAX),
	TotalMarks INT,
	TimeLimitMinutes INT,
	DueDate DATETIME,
	IsPublished BIT DEFAULT 0
);

CREATE TABLE Question (
	QuestionID INT IDENTITY (1,1) PRIMARY KEY,
	AssessmentID INT FOREIGN KEY REFERENCES Assessment(AssessmentID),
	QuestionText NVARCHAR(MAX) NOT NULL,
	QuestionType NVARCHAR(50),
	Marks INT
);

CREATE TABLE QuestionOption (
	OptionID INT IDENTITY(1,1) PRIMARY KEY,
	QuestionID INT FOREIGN KEY REFERENCES Question(QuestionID),
	OptionText NVARCHAR(500) NOT NULL,
	IsCorrect BIT NOT NULL
);

CREATE TABLE AssessmentSubmission (
	SubmissionID INT IDENTITY(1,1) PRIMARY KEY, 
	AssessmentID INT FOREIGN KEY REFERENCES Assessment(AssessmentID),
	StudentID INT FOREIGN KEY REFERENCES Users(UserID),
	SubmittedAt DATETIME DEFAULT GETDATE(),
	TotalScore INT
);

CREATE TABLE SubmissionAnswer (
	AnswerID INT IDENTITY(1,1) PRIMARY KEY,
	SubmissionID INT FOREIGN KEY REFERENCES AssessmentSubmission(SubmissionID),
	QuestionID INT FOREIGN KEY REFERENCES Question(QuestionID),
	SelectedOptionID INT FOREIGN KEY REFERENCES QuestionOption(OptionID),
	AnswerText NVARCHAR(MAX),
	MarksAwarded INT
);