//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PythonAcademy.Admin
{


    public partial class AdminReports
    {

        /// <summary>
        /// btnExportCsv control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnExportCsv;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// ddlReportType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlReportType;

        /// <summary>
        /// txtStartDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;

        /// <summary>
        /// txtEndDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEndDate;

        /// <summary>
        /// btnGenerateReport control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGenerateReport;

        /// <summary>
        /// lblMetricOneTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMetricOneTitle;

        /// <summary>
        /// lblMetricOneValue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMetricOneValue;

        /// <summary>
        /// lblMetricOneCaption control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMetricOneCaption;

        /// <summary>
        /// lblMetricTwoTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMetricTwoTitle;

        /// <summary>
        /// lblMetricTwoValue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMetricTwoValue;

        /// <summary>
        /// lblMetricTwoCaption control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMetricTwoCaption;

        /// <summary>
        /// lblMetricThreeTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMetricThreeTitle;

        /// <summary>
        /// lblMetricThreeValue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMetricThreeValue;

        /// <summary>
        /// lblMetricThreeCaption control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMetricThreeCaption;

        /// <summary>
        /// lblReportSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblReportSummary;

        /// <summary>
        /// gvReportData control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvReportData;
    }
}
