//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PythonAcademy.Admin
{


    public partial class Verification
    {

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// lblQueueSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblQueueSummary;

        /// <summary>
        /// gvPendingUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvPendingUsers;
    }
}
