//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PythonAcademy
{


    public partial class SubmitExercise
    {

        /// <summary>
        /// lblAssessmentTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAssessmentTitle;

        /// <summary>
        /// lblModuleTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblModuleTitle;

        /// <summary>
        /// pnlMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMsg;

        /// <summary>
        /// msgBox control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl msgBox;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// rptQuestions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptQuestions;

        /// <summary>
        /// btnSubmit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
