//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PythonAcademy
{


    public partial class TakeAssessment
    {

        /// <summary>
        /// pnlError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlError;

        /// <summary>
        /// lblError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblError;

        /// <summary>
        /// pnlQuiz control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlQuiz;

        /// <summary>
        /// lblQuizTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblQuizTitle;

        /// <summary>
        /// rptQuestions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptQuestions;

        /// <summary>
        /// btnSubmit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
