//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PythonAcademy
{


    public partial class ViewResults
    {

        /// <summary>
        /// pnlError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlError;

        /// <summary>
        /// lblError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblError;

        /// <summary>
        /// pnlResults control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlResults;

        /// <summary>
        /// lblAssessmentTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAssessmentTitle;

        /// <summary>
        /// lblTotalScore control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalScore;

        /// <summary>
        /// rptResults control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptResults;

        /// <summary>
        /// btnBackDashboard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBackDashboard;
    }
}
